name: Build do Projeto Spring Boot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.generate_tag.outputs.sha }} 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verificar codificação dos arquivos
        run: |
          file src/main/resources/application.properties || echo "Arquivo não encontrado"
          iconv -f UTF-8 -t UTF-8 src/main/resources/application.properties > /dev/null || echo "Codificação inválida"

      - name: Compilar com Maven
        run: mvn -B clean package --file pom.xml

      - name: Executar testes
        run: mvn test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: amakusashirou/funcionarios:${{ steps.generate_tag.outputs.sha }},amakusashirou/funcionarios:latest

   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     needs: build

     steps: 
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          repository: LuisCarlosJp/funcionarios-k8s
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Instalar o Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize_version: v5.7.1

      - name: Atualizando os valores da imagem
        run: |
          cd kubernetes
          kustomize edit set imagem imagem=amakusashirou/funcionarios:${{ needs.build.outputs.image_sha }}

      - name: Criando commit tag da imagem
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git add .
          git commit -m "Mudando a tag da imagem"
          git push
